/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestionAgent (void);
GtkWidget* create_acceuil (void);
GtkWidget* create_windowvols (void);
GtkWidget* create_windowajout (void);
GtkWidget* create_windowmodif (void);
GtkWidget* create_window1 (void);
GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_window0 (void);
GtkWidget* create_fenetre_modifier (void);
GtkWidget* create_ajout (void);
GtkWidget* create_modifier (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_fenetre_supprimer (void);
GtkWidget* create_reservationzarif (void);
GtkWidget* create_ajoutreservation (void);
GtkWidget* create_modifreservation (void);
GtkWidget* create_supprimerreservation (void);
GtkWidget* create_reservation (void);
GtkWidget* create_Gestion_Client_WM (void);
GtkWidget* create_reclamation (void);
GtkWidget* create_window2 (void);
