/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *gestionAgent;
  GtkWidget *acceuil;
  GtkWidget *windowvols;
  GtkWidget *windowajout;
  GtkWidget *windowmodif;
  GtkWidget *window1;
  GtkWidget *fenetre_ajout;
  GtkWidget *window0;
  GtkWidget *fenetre_modifier;
  GtkWidget *ajout;
  GtkWidget *modifier;
  GtkWidget *supprimer;
  GtkWidget *fenetre_supprimer;
  GtkWidget *reservationzarif;
  GtkWidget *ajoutreservation;
  GtkWidget *modifreservation;
  GtkWidget *supprimerreservation;
  GtkWidget *reservation;
  GtkWidget *Gestion_Client_WM;
  GtkWidget *reclamation;
  GtkWidget *window2;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*gestionAgent = create_gestionAgent ();
  gtk_widget_show (gestionAgent);
  acceuil = create_acceuil ();
  gtk_widget_show (acceuil);
  windowvols = create_windowvols ();
  gtk_widget_show (windowvols);
  windowajout = create_windowajout ();
  gtk_widget_show (windowajout);
  windowmodif = create_windowmodif ();
  gtk_widget_show (windowmodif);
  window1 = create_window1 ();
  gtk_widget_show (window1);
  fenetre_ajout = create_fenetre_ajout ();
  gtk_widget_show (fenetre_ajout);
  window0 = create_window0 ();
  gtk_widget_show (window0);
  fenetre_modifier = create_fenetre_modifier ();
  gtk_widget_show (fenetre_modifier);
  ajout = create_ajout ();
  gtk_widget_show (ajout);
  modifier = create_modifier ();
  gtk_widget_show (modifier);
  supprimer = create_supprimer ();
  gtk_widget_show (supprimer);
  fenetre_supprimer = create_fenetre_supprimer ();
  gtk_widget_show (fenetre_supprimer);
  reservationzarif = create_reservationzarif ();
  gtk_widget_show (reservationzarif);
  ajoutreservation = create_ajoutreservation ();
  gtk_widget_show (ajoutreservation);
  modifreservation = create_modifreservation ();
  gtk_widget_show (modifreservation);
  supprimerreservation = create_supprimerreservation ();
  gtk_widget_show (supprimerreservation);
  reservation = create_reservation ();
  gtk_widget_show (reservation);
  Gestion_Client_WM = create_Gestion_Client_WM ();
  gtk_widget_show (Gestion_Client_WM);
  reclamation = create_reclamation ();
  gtk_widget_show (reclamation);*/
  window2 = create_window2 ();
  gtk_widget_show (window2);

  gtk_main ();
  return 0;
}

